version: "3.8"

services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: geodb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: ./backend
    container_name: geoapp
    command:
      [
        "./wait-for-db.sh",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://user:password@db:3306/geodb

volumes:
  db_data:
